#!/usr/bin/env bash
set -euo pipefail

# Audit Field Kit — Run Full Audit
# Usage: ./scripts/run-audit.sh <client-id>

CLIENT_ID="${1:?Usage: $0 <client-id>}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

cd "$REPO_DIR"

# Validate client exists
if [ ! -d "clients/$CLIENT_ID" ]; then
    echo "Error: Client '$CLIENT_ID' not found in clients/"
    echo "Run ./scripts/init-client.sh $CLIENT_ID first"
    exit 1
fi

# Validate required files
for f in scoping.yaml benchmarks.yaml; do
    if [ ! -f "clients/$CLIENT_ID/$f" ]; then
        echo "Error: Missing clients/$CLIENT_ID/$f"
        exit 1
    fi
done

echo "=== Audit Field Kit ==="
echo "Client: $CLIENT_ID"
echo "Date:   $(date -u +%Y-%m-%d)"
echo ""

# Ensure work directories exist
mkdir -p work/{graph,evidence,findings,reports}

# 1. Load client config
echo "[1/4] Loading client configuration..."
python3 -c "
from lib.utils.config import ConfigLoader
config = ConfigLoader('clients')
cfg = config.load_client_config('$CLIENT_ID')
creds = config.load_credentials('$CLIENT_ID')
print(f'  Targets: {len(cfg[\"scoping\"].get(\"targets\", []))}')
print(f'  Benchmarks: {cfg[\"benchmarks\"].get(\"selected\", [])}')
"

# 2. Discover skills
echo "[2/4] Discovering audit skills..."
./scripts/list-skills.sh "$CLIENT_ID"

# 3. Collect evidence (per skill)
echo "[3/4] Collecting evidence..."
# TODO: Orchestrator-driven collection per domain
# For now, list what would be collected
for skill_dir in skills/cloud/azure skills/identity/active-directory skills/container/kubernetes; do
    if [ -f "$skill_dir/SKILL.md" ]; then
        echo "  - Found skill: $skill_dir"
    fi
done

# 4. Generate report placeholder
echo "[4/4] Generating report..."
mkdir -p "work/reports/$CLIENT_ID"
cat > "work/reports/$CLIENT_ID/audit-report.md" <<EOF
# Audit Report — $CLIENT_ID
**Generated:** $(date -u)
**Tool:** Audit Field Kit

This report was generated by the Audit Field Kit.
EOF

echo ""
echo "=== Done ==="
echo "Report: work/reports/$CLIENT_ID/audit-report.md"